### ISSUE TITLE
BNW 2.0 - patching "[h]BNW Summon Descriptions with Menu Edits.ips"[rc3] messes up in-game Config menu

### ISSUE THREAD

**Issue by singaporygon** [SirNewtonFig/BNWSummonDescriptions#1]
BNW 2.0 - patching "[h]BNW Summon Descriptions with Menu Edits.ips"[rc3] messes up in-game Config menu

Also says failed checksum when starting up

And still happens with both rc1 headered ips files

Thanks for your work with this

**Comment by SirNewtonFig** [comment]
This patch may actually be dependent upon some of the work in the BNW 2.1 beta, as that is what it was built against, so it's very possible that 2.0 doesn't support it.

That said, it's already Incorporated in the latest BNW 2.1 beta release (and furthermore, 2.1 is almost out of beta), so my motivation to make this backwards compatible with 2.0 is pretty low.

If you'd like to take 2.1 for a spin, hop on over to the NG+ Discord and ask around in the #brave-new-world channel there, we'll get you hooked up. Follow the "Chat" link from the forums for the Discord invite link: http://ngplus.net/index.php?/forums/forum/5-final-fantasy-vi-brave-new-world/#
